---
- hosts: web
  name: "Web Deployment"
  tasks: 
  - name: Install Apache Packages
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Install Httpd Packages
    yum: name=httpd state=present 
    when: ansible_os_family == "RedHat"

  - name: Bring up Apache Service 
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"

  - name: Bring up Httpd Service 
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"


  - name: Deploy Common Index Web Page
    copy: src=files/index.html dest=/var/www/html/index.html

  - name: Check Who am I 
    command: whoami
    register: username

  - debug: msg="Welcome to ansible web deployment playbook"

  - debug: var=username
